create table if not exists public.atendimento_medico_exames (
  id bigint generated by default as identity primary key,
  tipo varchar(30) not null,
  exame varchar(100) not null,
  constraint atendimento_medico_exames_unique unique (tipo, exame)
);

create index if not exists atendimento_medico_exames_tipo_idx
on public.atendimento_medico_exames(tipo);

create index if not exists atendimento_medico_exames_exame_idx
on public.atendimento_medico_exames(exame);

alter table public.atendimento_medico_exames enable row level security;

create policy "atendimento medico exames authenticated read"
on public.atendimento_medico_exames
for select to authenticated using (true);

create policy "atendimento medico exames admin write"
on public.atendimento_medico_exames
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
