create table if not exists public.auxiliares (
  id bigint generated by default as identity primary key,
  grupo text not null,
  nome varchar(100) not null,
  ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(grupo, nome)
);

create index if not exists auxiliares_grupo_idx on public.auxiliares(grupo, ativo, ordem, nome);

create trigger auxiliares_touch_updated_at
before update on public.auxiliares
for each row execute function public.touch_updated_at();

alter table public.auxiliares enable row level security;

create policy "auxiliares authenticated read" on public.auxiliares
for select to authenticated using (true);

create policy "auxiliares admin write" on public.auxiliares
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
