create table if not exists public.associados_contribuicoes (
  id bigint generated by default as identity primary key,
  associado_id bigint not null default 0,
  contribuicao_id bigint not null default 0,
  created_at timestamptz not null default now(),
  dt_pg timestamptz,
  constraint associados_contribuicoes_associado_id_fkey
    foreign key (associado_id) references public.associados(id) on delete cascade,
  constraint associados_contribuicoes_contribuicao_id_fkey
    foreign key (contribuicao_id) references public.contribuicoes(id),
  constraint associados_contribuicoes_associado_contribuicao_key
    unique (associado_id, contribuicao_id)
);

create index if not exists associados_contribuicoes_associado_id_idx
on public.associados_contribuicoes(associado_id);

create index if not exists associados_contribuicoes_contribuicao_id_idx
on public.associados_contribuicoes(contribuicao_id);

alter table public.associados_contribuicoes enable row level security;

create policy "associados_contribuicoes authenticated read" on public.associados_contribuicoes
for select to authenticated using (true);

create policy "associados_contribuicoes admin write" on public.associados_contribuicoes
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
