create table if not exists public.bancos (
  id bigint generated by default as identity primary key,
  ativo char(1) not null default 'S',
  banco_numero varchar(10) not null,
  banco_nome varchar(80) not null,
  agencia_numero varchar(20) not null,
  conta_numero varchar(30) not null,
  telefone varchar(20),
  nome_gerente varchar(80),
  logotipo_path text,
  nosso_numero_inicio bigint not null default 0,
  nosso_numero_fim bigint not null default 0,
  nosso_numero_proximo bigint not null default 0,
  codigo_cedente varchar(30),
  carteira varchar(20),
  padrao_retorno varchar(20) not null default 'FEBRABAN240',
  tx_bancaria numeric(10,2) not null default 0,
  multa_percentual numeric(7,4) not null default 0,
  juros_dia_percentual numeric(7,4) not null default 0,
  desconto_percentual numeric(7,4) not null default 0,
  outros_acrescimos numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bancos_ativo_check check (ativo in ('S', 'N')),
  constraint bancos_padrao_retorno_check check (padrao_retorno in ('CNAB400', 'FEBRABAN240')),
  constraint bancos_nosso_numero_range_check check (nosso_numero_fim >= nosso_numero_inicio),
  constraint bancos_nosso_numero_proximo_check check (nosso_numero_proximo >= nosso_numero_inicio and nosso_numero_proximo <= nosso_numero_fim)
);

create unique index if not exists bancos_conta_unique
on public.bancos(banco_numero, agencia_numero, conta_numero);

drop trigger if exists bancos_touch_updated_at on public.bancos;
create trigger bancos_touch_updated_at
before update on public.bancos
for each row execute function public.touch_updated_at();

alter table public.bancos enable row level security;

drop policy if exists "bancos authenticated read" on public.bancos;
create policy "bancos authenticated read" on public.bancos
for select to authenticated using (true);

drop policy if exists "bancos admin write" on public.bancos;
create policy "bancos admin write" on public.bancos
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());

insert into storage.buckets(id, name, public)
values ('bancos-logotipos', 'bancos-logotipos', true)
on conflict (id) do nothing;

drop policy if exists "bancos logotipo read" on storage.objects;
create policy "bancos logotipo read" on storage.objects
for select using (bucket_id = 'bancos-logotipos' and auth.role() = 'authenticated');

drop policy if exists "bancos logotipo upload" on storage.objects;
create policy "bancos logotipo upload" on storage.objects
for insert with check (bucket_id = 'bancos-logotipos' and public.current_user_is_admin());

drop policy if exists "bancos logotipo update" on storage.objects;
create policy "bancos logotipo update" on storage.objects
for update using (bucket_id = 'bancos-logotipos' and public.current_user_is_admin())
with check (bucket_id = 'bancos-logotipos' and public.current_user_is_admin());

create table if not exists public.faturas (
  id bigint generated by default as identity primary key,
  sacado_tipo varchar(10) not null,
  associado_id bigint,
  empresa_id bigint,
  contribuicao_id bigint not null,
  banco_id bigint not null,
  competencia_mes integer not null,
  competencia_ano integer not null,
  dt_emissao date not null default current_date,
  dt_vencimento date not null,
  valor_base numeric(10,2) not null default 0,
  tx_bancaria numeric(10,2) not null default 0,
  multa_percentual numeric(7,4) not null default 0,
  juros_dia_percentual numeric(7,4) not null default 0,
  desconto_percentual numeric(7,4) not null default 0,
  outros_acrescimos numeric(10,2) not null default 0,
  valor_total numeric(10,2) generated always as (
    valor_base + tx_bancaria + outros_acrescimos - round((valor_base * desconto_percentual / 100), 2)
  ) stored,
  nosso_numero varchar(30),
  linha_digitavel varchar(120),
  situacao varchar(15) not null default 'ABERTA',
  created_by uuid default auth.uid(),
  updated_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint faturas_sacado_tipo_check check (sacado_tipo in ('ASSOCIADO', 'EMPRESA')),
  constraint faturas_sacado_check check (
    (sacado_tipo = 'ASSOCIADO' and associado_id is not null and empresa_id is null) or
    (sacado_tipo = 'EMPRESA' and empresa_id is not null and associado_id is null)
  ),
  constraint faturas_competencia_mes_check check (competencia_mes between 1 and 12),
  constraint faturas_situacao_check check (situacao in ('ABERTA', 'PAGA', 'CANCELADA')),
  constraint faturas_associado_id_fkey foreign key (associado_id) references public.associados(id),
  constraint faturas_empresa_id_fkey foreign key (empresa_id) references public.empresas(id),
  constraint faturas_contribuicao_id_fkey foreign key (contribuicao_id) references public.contribuicoes(id),
  constraint faturas_banco_id_fkey foreign key (banco_id) references public.bancos(id)
);

create unique index if not exists faturas_unique_sacado_competencia
on public.faturas(sacado_tipo, associado_id, empresa_id, contribuicao_id, competencia_mes, competencia_ano)
nulls not distinct;

create index if not exists faturas_banco_id_idx on public.faturas(banco_id);
create index if not exists faturas_contribuicao_id_idx on public.faturas(contribuicao_id);
create index if not exists faturas_dt_vencimento_idx on public.faturas(dt_vencimento);

drop trigger if exists faturas_touch_updated_at on public.faturas;
create trigger faturas_touch_updated_at
before update on public.faturas
for each row execute function public.touch_updated_at();

alter table public.faturas enable row level security;

drop policy if exists "faturas authenticated read" on public.faturas;
create policy "faturas authenticated read" on public.faturas
for select to authenticated using (true);

drop policy if exists "faturas admin write" on public.faturas;
create policy "faturas admin write" on public.faturas
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());

drop view if exists public.faturas_lista;
create view public.faturas_lista
with (security_invoker = true) as
select
  f.*,
  c.tipo as contribuicao_tipo,
  c.nm_contribuicao,
  b.banco_numero,
  b.banco_nome,
  b.agencia_numero,
  b.conta_numero,
  a.nome as associado_nome,
  a.cpf as associado_documento,
  e.nm_fantasia as empresa_nome,
  e.cei_cnpj as empresa_documento,
  pc.codinome as created_by_codinome,
  pc.full_name as created_by_nome,
  pu.codinome as updated_by_codinome,
  pu.full_name as updated_by_nome
from public.faturas f
join public.contribuicoes c on c.id = f.contribuicao_id
join public.bancos b on b.id = f.banco_id
left join public.associados a on a.id = f.associado_id
left join public.empresas e on e.id = f.empresa_id
left join public.profiles pc on pc.id = f.created_by
left join public.profiles pu on pu.id = f.updated_by;
