create table if not exists public.atendimento_medico_convenios_especialidades (
  id bigint generated by default as identity primary key,
  convenio_id bigint not null,
  especialidade_id bigint not null,
  created_at timestamptz not null default now(),
  constraint atendimento_medico_convenios_especialidades_convenio_fkey
    foreign key (convenio_id) references public.atendimento_medico_convenios(id) on delete cascade,
  constraint atendimento_medico_convenios_especialidades_especialidade_fkey
    foreign key (especialidade_id) references public.atendimento_medico_especialidades(id) on delete restrict,
  constraint atendimento_medico_convenios_especialidades_unique unique (convenio_id, especialidade_id)
);

create index if not exists atendimento_medico_convenios_especialidades_convenio_idx
on public.atendimento_medico_convenios_especialidades(convenio_id);

create index if not exists atendimento_medico_convenios_especialidades_especialidade_idx
on public.atendimento_medico_convenios_especialidades(especialidade_id);

alter table public.atendimento_medico_convenios_especialidades enable row level security;

create policy "atendimento medico convenios especialidades authenticated read"
on public.atendimento_medico_convenios_especialidades
for select to authenticated using (true);

create policy "atendimento medico convenios especialidades admin write"
on public.atendimento_medico_convenios_especialidades
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
