create table if not exists public.local_trabalho (
  id bigint generated by default as identity primary key,
  nome varchar(50) not null,
  email varchar(100),
  tel1 char(11),
  tel2 char(11),
  nm_contato varchar(50),
  endereco varchar(50),
  numero varchar(15),
  complemento varchar(30),
  bairro varchar(30),
  cidade varchar(30),
  uf char(2) not null default 'RJ',
  cep char(10),
  obs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists local_trabalho_nome_idx on public.local_trabalho(nome);
create index if not exists local_trabalho_cidade_idx on public.local_trabalho(cidade);

create trigger local_trabalho_touch_updated_at
before update on public.local_trabalho
for each row execute function public.touch_updated_at();

alter table public.local_trabalho enable row level security;

create policy "local trabalho authenticated read" on public.local_trabalho
for select to authenticated using (true);

create policy "local trabalho admin write" on public.local_trabalho
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
