create table if not exists public.empresas_contribuicoes (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null default 0,
  contribuicao_id bigint not null default 0,
  created_at timestamptz not null default now(),
  dt_pg timestamptz,
  constraint empresas_contribuicoes_empresa_id_fkey
    foreign key (empresa_id) references public.empresas(id) on delete cascade,
  constraint empresas_contribuicoes_contribuicao_id_fkey
    foreign key (contribuicao_id) references public.contribuicoes(id),
  constraint empresas_contribuicoes_empresa_contribuicao_key
    unique (empresa_id, contribuicao_id)
);

create index if not exists empresas_contribuicoes_empresa_id_idx
on public.empresas_contribuicoes(empresa_id);

create index if not exists empresas_contribuicoes_contribuicao_id_idx
on public.empresas_contribuicoes(contribuicao_id);

alter table public.empresas_contribuicoes enable row level security;

create policy "empresas_contribuicoes authenticated read" on public.empresas_contribuicoes
for select to authenticated using (true);

create policy "empresas_contribuicoes admin write" on public.empresas_contribuicoes
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
