create table if not exists public.atendimento_medico_convenio (
  id bigint generated by default as identity primary key,
  ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
  tipo_pessoa char(1) not null default 'J' check (tipo_pessoa in ('F', 'J')),
  nm_convenio varchar(50) not null,
  nm_responsavel varchar(50),
  cpf_cnpj varchar(14) not null,
  endereco varchar(50),
  numero varchar(15),
  complemento varchar(30),
  bairro varchar(30),
  cidade varchar(30),
  uf char(2) not null default 'RJ',
  cep char(10),
  tel1 char(11),
  tel2 char(11),
  tel3 char(11),
  obs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists atendimento_medico_convenio_nome_idx on public.atendimento_medico_convenio(nm_convenio);
create index if not exists atendimento_medico_convenio_cpf_cnpj_idx on public.atendimento_medico_convenio(cpf_cnpj);

create trigger atendimento_medico_convenio_touch_updated_at
before update on public.atendimento_medico_convenio
for each row execute function public.touch_updated_at();

alter table public.atendimento_medico_convenio enable row level security;

create policy "atendimento medico convenio authenticated read" on public.atendimento_medico_convenio
for select to authenticated using (true);

create policy "atendimento medico convenio admin write" on public.atendimento_medico_convenio
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
