create table if not exists public.atendimento_homologacao (
  id bigint generated by default as identity primary key,
  sede_id bigint not null,
  empresa_id bigint not null,
  dt_agendado timestamptz not null default now(),
  situacao varchar(10) not null default 'AGENDADO',
  nm_homologador varchar(50) not null,
  qtd integer not null default 0,
  obs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint atendimento_homologacao_sede_id_fkey
    foreign key (sede_id) references public.auxiliares(id),
  constraint atendimento_homologacao_empresa_id_fkey
    foreign key (empresa_id) references public.empresas(id),
  constraint atendimento_homologacao_situacao_check
    check (situacao in ('AGENDADO', 'ATENDIDO', 'CANCELADO')),
  constraint atendimento_homologacao_qtd_nonnegative
    check (qtd >= 0)
);

create index if not exists atendimento_homologacao_sede_id_idx
on public.atendimento_homologacao(sede_id);

create index if not exists atendimento_homologacao_empresa_id_idx
on public.atendimento_homologacao(empresa_id);

create index if not exists atendimento_homologacao_dt_agendado_idx
on public.atendimento_homologacao(dt_agendado);

drop trigger if exists atendimento_homologacao_touch_updated_at on public.atendimento_homologacao;
create trigger atendimento_homologacao_touch_updated_at
before update on public.atendimento_homologacao
for each row execute function public.touch_updated_at();

alter table public.atendimento_homologacao enable row level security;

drop policy if exists "atendimento_homologacao authenticated read" on public.atendimento_homologacao;
create policy "atendimento_homologacao authenticated read" on public.atendimento_homologacao
for select to authenticated using (true);

drop policy if exists "atendimento_homologacao admin write" on public.atendimento_homologacao;
create policy "atendimento_homologacao admin write" on public.atendimento_homologacao
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());

create or replace view public.atendimento_homologacao_lista as
select
  ah.id,
  ah.sede_id,
  ah.empresa_id,
  ah.dt_agendado,
  ah.situacao,
  ah.nm_homologador,
  ah.qtd,
  ah.obs,
  ah.created_at,
  ah.updated_at,
  sede.nome as nm_sede,
  empresa.nm_fantasia as nm_empresa,
  empresa.razao_social,
  empresa.cei_cnpj
from public.atendimento_homologacao ah
join public.auxiliares sede on sede.id = ah.sede_id
join public.empresas empresa on empresa.id = ah.empresa_id;
