create table if not exists public.contribuicao (
  id bigint generated by default as identity primary key,
  tipo char(3) not null unique,
  nm_contribuicao varchar(50) not null,
  dia_vencimento integer not null default 1 check (dia_vencimento between 1 and 31),
  instrucao varchar(100),
  valor_base numeric(10,2) not null default 0.00,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger contribuicao_touch_updated_at
before update on public.contribuicao
for each row execute function public.touch_updated_at();

alter table public.contribuicao enable row level security;

create policy "contribuicao authenticated read" on public.contribuicao
for select to authenticated using (true);

create policy "contribuicao admin write" on public.contribuicao
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
