create table if not exists public.cnae (
  id bigint generated by default as identity primary key,
  codigo_cnae varchar(20) not null unique,
  descricao varchar(150) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cnae_descricao_idx on public.cnae(descricao);

create trigger cnae_touch_updated_at
before update on public.cnae
for each row execute function public.touch_updated_at();

alter table public.cnae enable row level security;

create policy "cnae authenticated read" on public.cnae
for select to authenticated using (true);

create policy "cnae admin write" on public.cnae
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
