do $$
begin
  if to_regclass('public.dependentes') is not null and to_regclass('public.associados_dependentes') is null then
    alter table public.dependentes rename to associados_dependentes;
  end if;
end $$;

create table if not exists public.associados_dependentes (
  id bigint generated by default as identity primary key,
  associado_id bigint not null default 0,
  dt_nascimento date not null default current_date,
  nm_dependente varchar(50) not null,
  cpf varchar(11),
  sexo char(1) not null default 'M',
  estado_civil varchar(15) not null default '',
  parentesco varchar(15) not null default '',
  telefone char(11),
  obs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'nome'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'nm_dependente'
  ) then
    alter table public.associados_dependentes rename column nome to nm_dependente;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'data_nascimento'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'dt_nascimento'
  ) then
    alter table public.associados_dependentes rename column data_nascimento to dt_nascimento;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'tel1'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'telefone'
  ) then
    alter table public.associados_dependentes rename column tel1 to telefone;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'observacao'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'associados_dependentes' and column_name = 'obs'
  ) then
    alter table public.associados_dependentes rename column observacao to obs;
  end if;
end $$;

alter table public.associados_dependentes
  alter column associado_id set default 0,
  alter column nm_dependente type varchar(50) using left(nm_dependente, 50),
  alter column nm_dependente set not null,
  alter column cpf type varchar(11) using left(regexp_replace(coalesce(cpf, ''), '\D', '', 'g'), 11),
  alter column sexo type char(1) using left(coalesce(nullif(sexo, ''), 'M'), 1),
  alter column sexo set default 'M',
  alter column estado_civil type varchar(15) using left(coalesce(estado_civil, ''), 15),
  alter column parentesco type varchar(15) using left(coalesce(parentesco, ''), 15),
  alter column telefone type char(11) using left(regexp_replace(coalesce(telefone, ''), '\D', '', 'g'), 11);

update public.associados_dependentes
set
  dt_nascimento = coalesce(dt_nascimento, current_date),
  sexo = coalesce(nullif(sexo, ''), 'M'),
  estado_civil = coalesce(estado_civil, ''),
  parentesco = coalesce(parentesco, '');

alter table public.associados_dependentes
  alter column dt_nascimento set not null,
  alter column sexo set not null,
  alter column estado_civil set not null,
  alter column parentesco set not null;

create index if not exists associados_dependentes_associado_idx on public.associados_dependentes(associado_id);
create index if not exists associados_dependentes_nome_idx on public.associados_dependentes(nm_dependente);

drop trigger if exists dependentes_touch_updated_at on public.associados_dependentes;
drop trigger if exists associados_dependentes_touch_updated_at on public.associados_dependentes;
create trigger associados_dependentes_touch_updated_at
before update on public.associados_dependentes
for each row execute function public.touch_updated_at();

alter table public.associados_dependentes enable row level security;

drop policy if exists "dependentes read" on public.associados_dependentes;
drop policy if exists "dependentes save" on public.associados_dependentes;
drop policy if exists "associados dependentes authenticated read" on public.associados_dependentes;
drop policy if exists "associados dependentes admin write" on public.associados_dependentes;

create policy "associados dependentes authenticated read" on public.associados_dependentes
for select to authenticated using (true);

create policy "associados dependentes admin write" on public.associados_dependentes
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
