create table if not exists public.empresa (
  id bigint generated by default as identity primary key,
  user_resp_id integer not null default 0,
  estabelecimento_id integer not null default 1,
  estabelecimento_tipo_id integer not null default 1,
  escritorio_id integer not null default 0,
  ramo_atividade_id integer not null default 0,
  convencao_id integer not null default 0,
  cnae_id integer not null default 0,
  tipo_cei_cnpj integer not null default 1,
  dt_inicio_atividades date,
  ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
  razao_social varchar(100) not null,
  nm_fantasia varchar(50) not null,
  cei_cnpj varchar(14) not null unique,
  insc_estadual varchar(25),
  nm_contato1 varchar(40),
  nm_contato2 varchar(40),
  nm_contato3 varchar(40),
  email1 varchar(100),
  email2 varchar(100),
  email3 varchar(100),
  tel1 char(11),
  tel2 char(11),
  tel3 char(11),
  site varchar(100),
  endereco varchar(50),
  numero varchar(15),
  complemento varchar(30),
  bairro varchar(30),
  cidade varchar(30),
  uf char(2) not null default 'RJ',
  cep char(10),
  capital_social numeric(10,2) not null default 0.00,
  obs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists empresa_razao_social_idx on public.empresa(razao_social);
create index if not exists empresa_nm_fantasia_idx on public.empresa(nm_fantasia);
create index if not exists empresa_cidade_idx on public.empresa(cidade);

create trigger empresa_touch_updated_at
before update on public.empresa
for each row execute function public.touch_updated_at();

alter table public.empresa enable row level security;

create policy "empresa authenticated read" on public.empresa
for select to authenticated using (true);

create policy "empresa admin write" on public.empresa
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
