create table if not exists public.atendimento_medico_itens (
  id bigint generated by default as identity primary key,
  atendimento_id bigint not null,
  item_id bigint not null,
  tipo text not null default 'ESPECIALIDADE',
  descricao text not null,
  created_at timestamptz not null default now(),
  constraint atendimento_medico_itens_atendimento_fkey
    foreign key (atendimento_id) references public.atendimento_medico(id) on delete cascade,
  constraint atendimento_medico_itens_item_fkey
    foreign key (item_id) references public.auxiliares(id) on delete restrict,
  constraint atendimento_medico_itens_unique unique (atendimento_id, item_id, tipo)
);

create index if not exists atendimento_medico_itens_atendimento_idx
on public.atendimento_medico_itens(atendimento_id);

create index if not exists atendimento_medico_itens_item_idx
on public.atendimento_medico_itens(item_id);

alter table public.atendimento_medico_itens enable row level security;

create policy "atendimento_medico_itens authenticated read" on public.atendimento_medico_itens
for select to authenticated using (true);

create policy "atendimento_medico_itens admin write" on public.atendimento_medico_itens
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
