create table if not exists public.escritorio (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null default 0,
  razao_social varchar(100) not null,
  nm_fantasia varchar(50) not null,
  cpf_cnpj varchar(25) not null unique,
  email varchar(100),
  tel1 char(11),
  tel2 char(11),
  nm_contato varchar(50),
  endereco varchar(50),
  numero varchar(15),
  complemento varchar(30),
  bairro varchar(30),
  cidade varchar(30),
  uf char(2) not null default 'RJ',
  cep char(10),
  obs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists escritorio_razao_social_idx on public.escritorio(razao_social);
create index if not exists escritorio_nm_fantasia_idx on public.escritorio(nm_fantasia);

create trigger escritorio_touch_updated_at
before update on public.escritorio
for each row execute function public.touch_updated_at();

alter table public.escritorio enable row level security;

create policy "escritorio authenticated read" on public.escritorio
for select to authenticated using (true);

create policy "escritorio admin write" on public.escritorio
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
