create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  codinome text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.modules (
  key text primary key,
  label text not null,
  position integer not null default 0
);

insert into public.modules(key, label, position)
values ('associados', 'Associados', 10)
on conflict (key) do update set label = excluded.label, position = excluded.position;

create table if not exists public.module_permissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_key text not null references public.modules(key) on delete cascade,
  can_access boolean not null default false,
  can_save boolean not null default false,
  can_delete boolean not null default false,
  created_at timestamptz not null default now(),
  unique(user_id, module_key)
);

create table if not exists public.lookup_items (
  id bigint generated by default as identity primary key,
  kind text not null,
  label text not null,
  active boolean not null default true,
  legacy_id integer,
  created_at timestamptz not null default now(),
  unique(kind, label)
);

create table if not exists public.empresas (
  id bigint generated by default as identity primary key,
  legacy_id integer unique,
  nome_fantasia text not null,
  razao_social text,
  cnpj text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.associados (
  id bigint generated by default as identity primary key,
  legacy_id integer unique,
  empresa_id bigint references public.empresas(id),
  local_trabalho_id bigint references public.lookup_items(id),
  local_pagamento_id bigint references public.lookup_items(id),
  escolaridade_id bigint references public.lookup_items(id),
  funcao_id bigint references public.lookup_items(id),
  situacao_id bigint references public.lookup_items(id),
  ativo boolean not null default true,
  matricula text,
  matricula_empresa text,
  nome text not null,
  cpf text not null,
  rg text,
  sexo text check (sexo is null or sexo in ('M', 'F')),
  estado_civil text,
  data_cadastro date not null default current_date,
  data_categoria date,
  data_nascimento date,
  data_admissao date,
  data_situacao date,
  data_ficha date,
  data_recadastro date,
  endereco text,
  complemento text,
  bairro text,
  cidade text,
  uf char(2),
  cep text,
  tel1 text,
  tel2 text,
  tel3 text,
  email text,
  site text,
  pis text,
  ctps text,
  ctps_serie text,
  salario numeric(12,2),
  posto_trabalho text,
  masterclin char(1),
  observacao text,
  foto_path text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists associados_cpf_unique on public.associados(cpf);
create unique index if not exists associados_matricula_unique on public.associados(matricula) where matricula is not null and matricula <> '';
create index if not exists associados_nome_idx on public.associados using gin (to_tsvector('portuguese', nome));

create table if not exists public.dependentes (
  id bigint generated by default as identity primary key,
  legacy_id integer unique,
  associado_id bigint not null references public.associados(id) on delete cascade,
  nome text not null,
  cpf text,
  rg text,
  sexo text,
  parentesco text,
  estado_civil text,
  data_nascimento date,
  tel1 text,
  odonto boolean not null default false,
  observacao text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id bigint,
  action text not null,
  old_data jsonb,
  new_data jsonb,
  user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch_updated_at before update on public.profiles for each row execute function public.touch_updated_at();
create trigger empresas_touch_updated_at before update on public.empresas for each row execute function public.touch_updated_at();
create trigger associados_touch_updated_at before update on public.associados for each row execute function public.touch_updated_at();
create trigger dependentes_touch_updated_at before update on public.dependentes for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;

create or replace function public.can_access_module(module_key text, action_key text default 'access')
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_is_admin()
    or exists (
      select 1 from public.module_permissions p
      where p.user_id = auth.uid()
        and p.module_key = can_access_module.module_key
        and case coalesce(action_key, 'access')
          when 'save' then p.can_save
          when 'delete' then p.can_delete
          else p.can_access
        end
    );
$$;

create or replace view public.associados_lista as
select
  a.id,
  a.ativo,
  a.matricula,
  a.nome,
  a.cpf,
  a.tel1,
  a.email,
  a.foto_path,
  e.nome_fantasia as empresa_nome,
  s.label as situacao_nome
from public.associados a
left join public.empresas e on e.id = a.empresa_id
left join public.lookup_items s on s.id = a.situacao_id;

create or replace function public.save_associado(payload jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id bigint := nullif(payload->>'id', '')::bigint;
  saved_id bigint;
  before_row jsonb;
begin
  if not public.can_access_module('associados', 'save') then
    raise exception 'Sem permissão para salvar associado.' using errcode = '42501';
  end if;

  if target_id is not null then
    select to_jsonb(a) into before_row from public.associados a where a.id = target_id;
    update public.associados set
      ativo = coalesce((payload->>'ativo')::boolean, true),
      matricula = nullif(upper(trim(payload->>'matricula')), ''),
      matricula_empresa = nullif(upper(trim(payload->>'matricula_empresa')), ''),
      nome = upper(trim(payload->>'nome')),
      cpf = regexp_replace(payload->>'cpf', '\\D', '', 'g'),
      rg = nullif(upper(trim(payload->>'rg')), ''),
      sexo = nullif(payload->>'sexo', ''),
      estado_civil = nullif(upper(trim(payload->>'estado_civil')), ''),
      empresa_id = nullif(payload->>'empresa_id', '')::bigint,
      situacao_id = nullif(payload->>'situacao_id', '')::bigint,
      local_trabalho_id = nullif(payload->>'local_trabalho_id', '')::bigint,
      local_pagamento_id = nullif(payload->>'local_pagamento_id', '')::bigint,
      escolaridade_id = nullif(payload->>'escolaridade_id', '')::bigint,
      funcao_id = nullif(payload->>'funcao_id', '')::bigint,
      data_categoria = nullif(payload->>'data_categoria', '')::date,
      data_nascimento = nullif(payload->>'data_nascimento', '')::date,
      data_admissao = nullif(payload->>'data_admissao', '')::date,
      data_situacao = nullif(payload->>'data_situacao', '')::date,
      data_ficha = nullif(payload->>'data_ficha', '')::date,
      endereco = nullif(upper(trim(payload->>'endereco')), ''),
      complemento = nullif(upper(trim(payload->>'complemento')), ''),
      bairro = nullif(upper(trim(payload->>'bairro')), ''),
      cidade = nullif(upper(trim(payload->>'cidade')), ''),
      uf = nullif(upper(trim(payload->>'uf')), ''),
      cep = nullif(payload->>'cep', ''),
      tel1 = nullif(payload->>'tel1', ''),
      tel2 = nullif(payload->>'tel2', ''),
      tel3 = nullif(payload->>'tel3', ''),
      email = nullif(lower(trim(payload->>'email')), ''),
      pis = nullif(payload->>'pis', ''),
      ctps = nullif(upper(trim(payload->>'ctps')), ''),
      ctps_serie = nullif(upper(trim(payload->>'ctps_serie')), ''),
      salario = nullif(payload->>'salario', '')::numeric,
      posto_trabalho = nullif(upper(trim(payload->>'posto_trabalho')), ''),
      masterclin = nullif(upper(trim(payload->>'masterclin')), ''),
      observacao = nullif(upper(trim(payload->>'observacao')), ''),
      updated_by = auth.uid()
    where id = target_id
    returning id into saved_id;
  else
    insert into public.associados(
      ativo, matricula, matricula_empresa, nome, cpf, rg, sexo, estado_civil, empresa_id, situacao_id,
      local_trabalho_id, local_pagamento_id, escolaridade_id, funcao_id, data_categoria, data_nascimento,
      data_admissao, data_situacao, data_ficha, endereco, complemento, bairro, cidade, uf, cep, tel1,
      tel2, tel3, email, pis, ctps, ctps_serie, salario, posto_trabalho, masterclin, observacao, created_by, updated_by
    ) values (
      coalesce((payload->>'ativo')::boolean, true), nullif(upper(trim(payload->>'matricula')), ''),
      nullif(upper(trim(payload->>'matricula_empresa')), ''), upper(trim(payload->>'nome')),
      regexp_replace(payload->>'cpf', '\\D', '', 'g'), nullif(upper(trim(payload->>'rg')), ''), nullif(payload->>'sexo', ''),
      nullif(upper(trim(payload->>'estado_civil')), ''), nullif(payload->>'empresa_id', '')::bigint,
      nullif(payload->>'situacao_id', '')::bigint, nullif(payload->>'local_trabalho_id', '')::bigint,
      nullif(payload->>'local_pagamento_id', '')::bigint, nullif(payload->>'escolaridade_id', '')::bigint,
      nullif(payload->>'funcao_id', '')::bigint, nullif(payload->>'data_categoria', '')::date,
      nullif(payload->>'data_nascimento', '')::date, nullif(payload->>'data_admissao', '')::date,
      nullif(payload->>'data_situacao', '')::date, nullif(payload->>'data_ficha', '')::date,
      nullif(upper(trim(payload->>'endereco')), ''), nullif(upper(trim(payload->>'complemento')), ''),
      nullif(upper(trim(payload->>'bairro')), ''), nullif(upper(trim(payload->>'cidade')), ''),
      nullif(upper(trim(payload->>'uf')), ''), nullif(payload->>'cep', ''), nullif(payload->>'tel1', ''),
      nullif(payload->>'tel2', ''), nullif(payload->>'tel3', ''), nullif(lower(trim(payload->>'email')), ''),
      nullif(payload->>'pis', ''), nullif(upper(trim(payload->>'ctps')), ''), nullif(upper(trim(payload->>'ctps_serie')), ''),
      nullif(payload->>'salario', '')::numeric, nullif(upper(trim(payload->>'posto_trabalho')), ''),
      nullif(upper(trim(payload->>'masterclin')), ''), nullif(upper(trim(payload->>'observacao')), ''), auth.uid(), auth.uid()
    ) returning id into saved_id;
  end if;

  insert into public.audit_log(table_name, record_id, action, old_data, new_data, user_id)
  select 'associados', saved_id, case when target_id is null then 'insert' else 'update' end, before_row, to_jsonb(a), auth.uid()
  from public.associados a where a.id = saved_id;

  return saved_id;
end;
$$;

insert into storage.buckets(id, name, public)
values ('associados-fotos', 'associados-fotos', true)
on conflict (id) do update set public = excluded.public;

alter table public.profiles enable row level security;
alter table public.modules enable row level security;
alter table public.module_permissions enable row level security;
alter table public.lookup_items enable row level security;
alter table public.empresas enable row level security;
alter table public.associados enable row level security;
alter table public.dependentes enable row level security;
alter table public.audit_log enable row level security;

create policy "profiles self read" on public.profiles for select using (id = auth.uid() or public.current_user_is_admin());
create policy "profiles admin write" on public.profiles for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy "modules authenticated read" on public.modules for select to authenticated using (true);
create policy "permissions self read" on public.module_permissions for select using (user_id = auth.uid() or public.current_user_is_admin());
create policy "permissions admin write" on public.module_permissions for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy "lookup associados read" on public.lookup_items for select using (public.can_access_module('associados', 'access'));
create policy "lookup admin write" on public.lookup_items for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy "empresas associados read" on public.empresas for select using (public.can_access_module('associados', 'access'));
create policy "empresas admin write" on public.empresas for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy "associados read" on public.associados for select using (public.can_access_module('associados', 'access'));
create policy "associados save via rpc" on public.associados for all using (public.can_access_module('associados', 'save')) with check (public.can_access_module('associados', 'save'));
create policy "dependentes read" on public.dependentes for select using (public.can_access_module('associados', 'access'));
create policy "dependentes save" on public.dependentes for all using (public.can_access_module('associados', 'save')) with check (public.can_access_module('associados', 'save'));
create policy "audit admin read" on public.audit_log for select using (public.current_user_is_admin());
create policy "foto read" on storage.objects for select using (bucket_id = 'associados-fotos' and auth.role() = 'authenticated');
create policy "foto upload" on storage.objects for insert with check (bucket_id = 'associados-fotos' and public.can_access_module('associados', 'save'));
create policy "foto update" on storage.objects for update using (bucket_id = 'associados-fotos' and public.can_access_module('associados', 'save')) with check (bucket_id = 'associados-fotos' and public.can_access_module('associados', 'save'));
