create table if not exists public.atendimento_medico (
  id bigint generated by default as identity primary key,
  created_by bigint not null default 0,
  updated_by bigint not null default 0,
  convenio_id bigint not null,
  associado_id bigint not null,
  dependente_id bigint not null default 0,
  qtd integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  dt_agendado timestamptz not null default now(),
  situacao varchar(10) not null,
  tipo varchar(30) not null,
  obs text,
  constraint atendimento_medico_convenio_id_fkey
    foreign key (convenio_id) references public.atendimento_medico_convenios(id),
  constraint atendimento_medico_associado_id_fkey
    foreign key (associado_id) references public.associados(id)
);

create index if not exists atendimento_medico_convenio_id_idx
on public.atendimento_medico(convenio_id);

create index if not exists atendimento_medico_associado_id_idx
on public.atendimento_medico(associado_id);

create index if not exists atendimento_medico_dependente_id_idx
on public.atendimento_medico(dependente_id);

create index if not exists atendimento_medico_dt_agendado_idx
on public.atendimento_medico(dt_agendado);

alter table public.atendimento_medico enable row level security;

create policy "atendimento_medico authenticated read" on public.atendimento_medico
for select to authenticated using (true);

create policy "atendimento_medico admin write" on public.atendimento_medico
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
