create table if not exists public.atendimento_medico_especialidade (
  id bigint generated by default as identity primary key,
  tipo varchar(30) not null check (tipo in ('ESPECIALIDADE', 'FEZES-URINA', 'OUTROS', 'RADIOLOGIA', 'EXAME DE SANGUE', 'ULTRASSONOGRAFIA')),
  nm_especialidade varchar(50) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tipo, nm_especialidade)
);

create index if not exists atendimento_medico_especialidade_tipo_idx on public.atendimento_medico_especialidade(tipo, nm_especialidade);

create trigger atendimento_medico_especialidade_touch_updated_at
before update on public.atendimento_medico_especialidade
for each row execute function public.touch_updated_at();

alter table public.atendimento_medico_especialidade enable row level security;

create policy "atendimento medico especialidade authenticated read" on public.atendimento_medico_especialidade
for select to authenticated using (true);

create policy "atendimento medico especialidade admin write" on public.atendimento_medico_especialidade
for all using (public.current_user_is_admin())
with check (public.current_user_is_admin());
